server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgresql
    url: "jdbc:postgresql://localhost:5432/enterprise-service-db"
    username: "user"
    password: "password"
  flyway:
    enabled: false
springdoc:
  swagger-ui:
    url: "openapi.yaml"
security:
  oauth:
    vk:
      auth_url: "https://api.vk.com/method/users.get?fields=screen_name"
      api_version: "5.131"
    yandex:
      auth_url: "https://login.yandex.ru/info?format=json"
  jwt:
    secret: w7sc3prjHPy9bnpENY@==pAV$hA!Skn&
    expiration-ms: 100000000

user:
  default_picture_url: "https://sun9-west.userapi.com/sun9-63/s/v1/ig2/fJ-9qBXk2idaOSI1UN73seplDBp8PQO5e0ekB5y3TDKgjSUB2-08la0r9lnSqc9Xjw12oYaY1BCE3QcCTQCmD0ZJ.jpg?size=1124x1124&quality=95&type=album"
lobby_service:
  url: "http://localhost:8081/api"
  api:
    create_lobby_url: "/lobby/create"
    join_lobby_url: "/lobby/join"
    connection_info_url: "/lobby/connection-info"
    get_all_lobbies: "/lobby/all"
    change_game: "/lobby/change-game"
    info_for_start: "/lobby/info-for-start"
    send-game-session-connection-info: "/lobby/send-game-session-creation-info"
    send-game-session-creation-error-info: "/lobby/send-creation-error-info"
game_service:
  api:
    create: "/create-new"