version: '3.9'

services:
  enterprise-service:
    build: ./..
    image: jackal-game-enterprise-service
    container_name: jackal-game-enterprise-service
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:${DB_PROTOCOL}://${DB_HOST}:${DB_INNER_PORT}/${DB_NAME}"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - enterprise-service-db
    restart: always
  enterprise-service-db:
    image: postgres
    container_name: jackal-game-enterprise-service-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_OUTER_PORT}:${DB_INNER_PORT}